package edu.elon.honors.price.maker.action;							// GameStateWriter.writeHeader()
																	// GameStateWriter.writeHeader()
import edu.elon.honors.price.maker.action.*;						// GameStateWriter.writeHeader()
import edu.elon.honors.price.data.*;								// GameStateWriter.writeHeader()
import edu.elon.honors.price.data.types.*;							// GameStateWriter.writeHeader()
import edu.elon.honors.price.data.Event.Parameters.Iterator;		// GameStateWriter.writeHeader()
import edu.elon.honors.price.data.Event.Parameters;					// GameStateWriter.writeHeader()
import com.twp.platform.*;											// GameStateWriter.writeHeader()
import edu.elon.honors.price.physics.*;								// GameStateWriter.writeHeader()
import edu.elon.honors.price.input.*;								// GameStateWriter.writeHeader()
@SuppressWarnings("unused")											// GameStateWriter.writeHeader()
public interface GameState {										// GameStateWriter.writeHeader()
	public UIControl readUi(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public android.graphics.Rect readRegion(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public JoyStick readJoystick(int params) throws ParameterException;// GameStateWriter.writeHeader()
	public boolean readSwitch(Switch params) throws ParameterException;// GameStateWriter.writeHeader()
	public ObjectClass readObjectClass(int params) throws ParameterException;// GameStateWriter.writeHeader()
	public int readNumber(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public Point readPoint(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public Button readButton(int params) throws ParameterException;	// GameStateWriter.writeHeader()
	public Vector readVector(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public ActorClass readActorClass(int params) throws ParameterException;// GameStateWriter.writeHeader()
	public ObjectBody readObjectInstance(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public boolean readBoolean(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public ActorBody readActorInstance(Parameters params) throws ParameterException;// GameStateWriter.writeHeader()
	public int readVariable(Variable params) throws ParameterException;// GameStateWriter.writeHeader()
}																	// GameStateWriter.writeHeader()
