package edu.elon.honors.price.maker.action;							// ActionFactoryWriter.writeHeader()
																	// ActionFactoryWriter.writeHeader()
public class ActionFactory {										// ActionFactoryWriter.writeHeader()
	public static ActionInstance getInstance(int id) {				// ActionFactoryWriter.writeHeader()
		if (id == ActionSetSwitch.ID) return new ActionSetSwitch();	// ActionFactoryWriter.writeHeader()
		if (id == ActionSetVariable.ID) return new ActionSetVariable();// ActionFactoryWriter.writeHeader()
		if (id == ActionCreateActor.ID) return new ActionCreateActor();// ActionFactoryWriter.writeHeader()
		if (id == ActionDebugBox.ID) return new ActionDebugBox();	// ActionFactoryWriter.writeHeader()
		if (id == ActionMoveActor.ID) return new ActionMoveActor();	// ActionFactoryWriter.writeHeader()
		if (id == ActionTriggerActorBehavior.ID) return new ActionTriggerActorBehavior();// ActionFactoryWriter.writeHeader()
		if (id == ActionIf.ID) return new ActionIf();				// ActionFactoryWriter.writeHeader()
		if (id == ActionCreateObject.ID) return new ActionCreateObject();// ActionFactoryWriter.writeHeader()
		if (id == ActionMoveObject.ID) return new ActionMoveObject();// ActionFactoryWriter.writeHeader()
		if (id == ActionSetVelocity.ID) return new ActionSetVelocity();// ActionFactoryWriter.writeHeader()
		if (id == ActionDebugMessage.ID) return new ActionDebugMessage();// ActionFactoryWriter.writeHeader()
		if (id == ActionPointOperation.ID) return new ActionPointOperation();// ActionFactoryWriter.writeHeader()
		if (id == ActionChangeGravity.ID) return new ActionChangeGravity();// ActionFactoryWriter.writeHeader()
		if (id == ActionUIAction.ID) return new ActionUIAction();	// ActionFactoryWriter.writeHeader()
		if (id == ActionDestroyObject.ID) return new ActionDestroyObject();// ActionFactoryWriter.writeHeader()
		if (id == ActionDrawToScreen.ID) return new ActionDrawToScreen();// ActionFactoryWriter.writeHeader()
		if (id == ActionLoop.ID) return new ActionLoop();			// ActionFactoryWriter.writeHeader()
		return null;												// ActionFactoryWriter.writeHeader()
	}																// ActionFactoryWriter.writeHeader()
}																	// ActionFactoryWriter.writeHeader()
